project:
  type: book

book:
  title: "w-python-numpy-grundlagen"
  author:
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Maik Poetzsch
    - Sebastian Seipel
  date: today
  language: de-DE
  downloads: [pdf]
  chapters: 
    - index.qmd
    - skript/einleitung.qmd
    - skript/array_creation.qmd
    - skript/array_info.qmd
    - skript/array_calculation.qmd
    - skript/array_slicing.qmd
    - skript/array_manipulation.qmd
    - skript/array_read_n_write.qmd
    - skript/array_images.qmd
    - uebungen/uebung.qmd
  

bibliography: skript/references.bib

format:
  html:
    theme: [cosmo, theme.scss]
    lang: de
    tbl-cap-location: bottom
  pdf:
    documentclass: scrreprt
    lang: de

execute:
  freeze: auto

