project:
  type: book

book:
  title: "w-python-numpy-grundlagen"
  author:
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Maik Poetzsch
    - Sebastian Seipel
  date: today
  language: de-DE
  downloads: [pdf]

bibliography: skript/references.bib

format:
  html:
    theme: [cosmo, theme.scss]
    lang: de
    tbl-cap-location: bottom
  pdf:
    documentclass: scrreprt
    lang: de
    toc-depth: 1

execute:
  freeze: auto

profile:
  default: full
  group: 
    - [full, klausur]

